Bike/Controllers/BikeRoutesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bike.Data;
using Bike.Models;
using Route = Bike.Models.Route;
using Microsoft.AspNetCore.Authorization;

namespace Bike.Controllers
{
    public class BikeRoutesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BikeRoutesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BikeRoutes
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewData["Name"] = _context.BikeType.Select(d => new { id = d.BikeTypeId, Name = d.Name }).FirstOrDefault(d => d.id == id).Name;
            ViewData["IdBikeType"] = _context.BikeType.Select(d => new { id = d.BikeTypeId, Name = d.Name }).FirstOrDefault(d => d.id == id).id;

            var applicationDbContext = _context.Routes.Where(d => d.BikeTypeId == id).Include(r => r.Address1).Include(r => r.Address2).Include(r => r.BikeType);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: BikeRoutes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var route = await _context.Routes
                .Include(r => r.Address1)
                .Include(r => r.Address2)
                .Include(r => r.BikeType)
                .FirstOrDefaultAsync(m => m.RouteId == id);
            if (route == null)
            {
                return NotFound();
            }

            return View(route);
        }

        // GET: BikeRoutes/Create
        [Authorize(Roles = "Administrator, Guest")]
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewData["AddressId1"] = new SelectList(_context.Address, "AddressId", "FullAddress");
            ViewData["AddressId2"] = new SelectList(_context.Address, "AddressId", "FullAddress");
            ViewData["BikeTypeId"] = id;
            return View();
        }

        // POST: BikeRoutes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Guest")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RouteId,AddressId1,AddressId2,BikeTypeId,Time,TimeResult")] Route route)
        {
            if (ModelState.IsValid)
            {
                _context.Add(route);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = route.BikeTypeId });
            }
            ViewData["AddressId1"] = new SelectList(_context.Address, "AddressId", "FullAddress", route.AddressId1);
            ViewData["AddressId2"] = new SelectList(_context.Address, "AddressId", "FullAddress", route.AddressId2);
            ViewData["BikeTypeId"] = route.BikeTypeId;
            return View(route);
        }

        // GET: BikeRoutes/Edit/5
        [Authorize(Roles = "Administrator, Guest")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var route = await _context.Routes.FindAsync(id);
            if (route == null)
            {
                return NotFound();
            }
            ViewData["AddressId1"] = new SelectList(_context.Address, "AddressId", "FullAddress", route.AddressId1);
            ViewData["AddressId2"] = new SelectList(_context.Address, "AddressId", "FullAddress", route.AddressId2);
            ViewData["BikeTypeId"] = new SelectList(_context.BikeType, "BikeTypeId", "Name", route.BikeTypeId);
            ViewData["IdBikeType"] = route.BikeTypeId;
            return View(route);
        }

        // POST: BikeRoutes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Guest")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RouteId,AddressId1,AddressId2,BikeTypeId,Time,TimeResult")] Route route)
        {
            if (id != route.RouteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(route);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RouteExists(route.RouteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = route.BikeTypeId });
            }
            ViewData["AddressId1"] = new SelectList(_context.Address, "AddressId", "FullAddress", route.AddressId1);
            ViewData["AddressId2"] = new SelectList(_context.Address, "AddressId", "FullAddress", route.AddressId2);
            ViewData["BikeTypeId"] = new SelectList(_context.BikeType, "BikeTypeId", "Name", route.BikeTypeId);
            ViewData["IdBikeType"] = route.BikeTypeId;
            return View(route);
        }

        // GET: BikeRoutes/Delete/5
        [Authorize(Roles = "Administrator, Guest")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var route = await _context.Routes
                .Include(r => r.Address1)
                .Include(r => r.Address2)
                .Include(r => r.BikeType)
                .FirstOrDefaultAsync(m => m.RouteId == id);
            if (route == null)
            {
                return NotFound();
            }

            return View(route);
        }

        // POST: BikeRoutes/Delete/5
        [Authorize(Roles = "Administrator, Guest")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var route = await _context.Routes.FindAsync(id);
            _context.Routes.Remove(route);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = route.BikeTypeId });
        }

        private bool RouteExists(int id)
        {
          return (_context.Routes?.Any(e => e.RouteId == id)).GetValueOrDefault();
        }
    }
}

Bike/Controllers/BikeTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bike.Data;
using Bike.Models;
using Microsoft.AspNetCore.Authorization;

namespace Bike.Controllers
{
    public class BikeTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BikeTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BikeTypes
        public async Task<IActionResult> Index()
        {
              return _context.BikeType != null ? 
                          View(await _context.BikeType.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.BikeType'  is null.");
        }

        // GET: BikeTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BikeType == null)
            {
                return NotFound();
            }

            var bikeType = await _context.BikeType
                .FirstOrDefaultAsync(m => m.BikeTypeId == id);
            if (bikeType == null)
            {
                return NotFound();
            }

            return View(bikeType);
        }

        // GET: BikeTypes/Create
        [Authorize(Roles = "Administrator, Guest")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: BikeTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Guest")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BikeTypeId,Name,Complexity,Speed,Time")] BikeType bikeType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bikeType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bikeType);
        }

        // GET: BikeTypes/Edit/5
        [Authorize(Roles = "Administrator, Guest")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BikeType == null)
            {
                return NotFound();
            }

            var bikeType = await _context.BikeType.FindAsync(id);
            if (bikeType == null)
            {
                return NotFound();
            }
            return View(bikeType);
        }

        // POST: BikeTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Guest")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BikeTypeId,Name,Complexity,Speed,Time")] BikeType bikeType)
        {
            if (id != bikeType.BikeTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bikeType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BikeTypeExists(bikeType.BikeTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bikeType);
        }

        // GET: BikeTypes/Delete/5
        [Authorize(Roles = "Administrator, Guest")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BikeType == null)
            {
                return NotFound();
            }

            var bikeType = await _context.BikeType
                .FirstOrDefaultAsync(m => m.BikeTypeId == id);
            if (bikeType == null)
            {
                return NotFound();
            }

            return View(bikeType);
        }

        // POST: BikeTypes/Delete/5
        [Authorize(Roles = "Administrator, Guest")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BikeType == null)
            {
                return Problem("Entity set 'ApplicationDbContext.BikeType'  is null.");
            }
            var bikeType = await _context.BikeType.FindAsync(id);
            if (bikeType != null)
            {
                _context.BikeType.Remove(bikeType);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BikeTypeExists(int id)
        {
          return (_context.BikeType?.Any(e => e.BikeTypeId == id)).GetValueOrDefault();
        }
    }
}

Bike/Views/BikeTypes/Create.cshtml
@model Bike.Models.BikeType

@{
    ViewData["Title"] = "Create";
}

<h1>Добавить</h1>

<h4>Типы велосипедов</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Complexity" class="control-label"></label>
                <input asp-for="Complexity" class="form-control" />
                <span asp-validation-for="Complexity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Speed" class="control-label"></label>
                <input asp-for="Speed" class="form-control" />
                <span asp-validation-for="Speed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bike/Views/BikeTypes/Delete.cshtml
@model Bike.Models.BikeType

@{
    ViewData["Title"] = "Delete";
}

<h1>Удалить</h1>

<h3>Вы уверены, что хотите удалить запись?</h3>
<div>
    <h4>Типы велосипедов</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Complexity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Complexity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Speed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Speed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BikeTypeId" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Назад</a>
    </form>
</div>

Bike/Views/BikeTypes/Details.cshtml
@model Bike.Models.BikeType

@{
    ViewData["Title"] = "Details";
}

<h1>Детали</h1>

<div>
    <h4>Типы велосипедов</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Complexity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Complexity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Speed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Speed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BikeTypeId">Редактировать</a> |
    <a asp-action="Index">Назад</a>
</div>

Bike/Views/BikeTypes/Edit.cshtml
@model Bike.Models.BikeType

@{
    ViewData["Title"] = "Edit";
}

<h1>Редактировать</h1>

<h4>Типы велосипедов</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BikeTypeId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Complexity" class="control-label"></label>
                <input asp-for="Complexity" class="form-control" />
                <span asp-validation-for="Complexity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Speed" class="control-label"></label>
                <input asp-for="Speed" class="form-control" />
                <span asp-validation-for="Speed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bike/Views/BikeTypes/Index.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model IEnumerable<Bike.Models.BikeType>

@{
    ViewData["Title"] = "Index";
}

<h1>Типы велосипедов</h1>

<p>
    @if ((await AuthorizationService.AuthorizeAsync(User, "RequireAdministratorRole")).Succeeded || (await AuthorizationService.AuthorizeAsync(User, "RequireGuestRole")).Succeeded)
    {
        <a asp-action="Create">Добавить запись</a>
    }    
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Complexity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Speed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Time)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Complexity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Speed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                    <a asp-action="Index" asp-controller="BikeRoutes" asp-route-id="@item.BikeTypeId">Маршруты</a>
                    <a asp-action="Details" asp-route-id="@item.BikeTypeId">Детали</a>
                    @if ((await AuthorizationService.AuthorizeAsync(User, "RequireAdministratorRole")).Succeeded || (await AuthorizationService.AuthorizeAsync(User, "RequireGuestRole")).Succeeded)
                    {
                        <a asp-action="Edit" asp-route-id="@item.BikeTypeId">Редактировать</a>
                        <a asp-action="Delete" asp-route-id="@item.BikeTypeId">Удалить</a>
                    }  
            </td>
        </tr>
}
    </tbody>
</table>